<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class InitObjects extends Seeder
{
	public function run()
	{
		$objects = [
			[
				'objectObject' => 'como-conozco-a-mi-publico',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/como-conozco-a-mi-publico.zip',
				'objectTitle' => '¿Cómo conozco a mi público?',
				'objectDescription' => 'Estudiar y aplicar herramientas que permiten un conocimiento profundo del público y del contexto en el que se implementa una idea de negocio.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Entrevista, Grupo Focal, Etnografía, Público Objetivo, Entrevista Estructurada, Entrevista Semiestructurada, Entrevista No Estructurada, Etnografía, Emprendimiento, Emprendedor, Mercado, Empresa',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724986/thumbnails/como-conozco-a-mi-publico.png',
				'objectYoutube' => 'mN1YWm6TFR0',
				'objectFormat' => 'SCORM',
				'objectSize' => '29.03 Mb',
				'objectRequirement' => 'individual,colectivo, lider Formato => zip Requerimientos => Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => sietic@unicolmayor.edu.co Rol => Autor Fecha => 2015-05-21',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-04 20:21:13',
				'objectTopic' => 'Objeto de Aprendizaje Procedimental',
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 4,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'consejos-para-una-buena-narracion',
				'objectArea' => 'Ciencias sociales y humanas',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/consejos-para-una-buena-narracion.zip',
				'objectTitle' => 'Consejos para una buena narración',
				'objectDescription' => 'Este objeto de aprendizaje muestra las maneras y métodos adecuados para obtener una buena narración, compresión de lectura, ortografía',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Narración,Guion,Estructura,Película,Esencia,Relato,Personajes,Lectura,Interpretación',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724996/thumbnails/consejos-para-una-buena-narracion.png',
				'objectYoutube' => '3jNioGEswYQ',
				'objectFormat' => 'SCORM',
				'objectSize' => '7.65 MB',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '2.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2014-02-15',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-04 21:07:43',
				'objectTopic' => 'Objeto de Aprendizaje. Conceptual',
				'objectInteractivity' => 'Medio',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 4,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'comunicacion-verbal-y-no-verbal',
				'objectArea' => 'Ciencias sociales y humanas',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/comunicacion-verbal-y-no-verbal.zip',
				'objectTitle' => 'Comunicación verbal y no verbal',
				'objectDescription' => 'Este Objeto de Aprendizaje Complementario, acerca de la comunicación verbal y no verbal, está diseñado para que aprenda sobre las diferencias de la comunicación verbal y no verbal como también la importancia dentro de la oralidad (herramientas) Modificado',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'herramientas, verbal, deferencias, oralidad',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724991/thumbnails/comunicacion-verbal-y-no-verbal.png',
				'objectYoutube' => 'KIJ0GmqH-jU',
				'objectFormat' => 'SCORM',
				'objectSize' => '43.8 Mb',
				'objectRequirement' => 'individual,colectivo, lider Formato => zip Requerimientos => Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '2.0',
				'objectContributors' => '',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 19:15:26',
				'objectTopic' => 'Objeto de Aprendizaje. Conceptual',
				'objectInteractivity' => 'Medio',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 4,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'competencias-gerenciales',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/competencias-gerenciales.zip',
				'objectTitle' => 'Competencias Gerenciales',
				'objectDescription' => 'En este objeto se encuentran las generalidades que sirven para desarrollar las competencias gerenciales con el fin de ayudar a las diferentes organizaciones a tener un desempeño sobresaliente.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Competencias, Gerente, Entorno organizacional, Liderazgo',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724991/thumbnails/competencias-gerenciales.png',
				'objectYoutube' => '',
				'objectFormat' => 'SCORM',
				'objectSize' => '157 Mb',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => 'Montar en plataforma Moodle',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2016-07-08',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 5,
				'objectViews' => 0,
				'isObjectActive' => 0
			],
			[
				'objectObject' => 'conceptos-modernos-de-administracion',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/conceptos-modernos-de-administracion.zip',
				'objectTitle' => 'Conceptos Modernos de Administración',
				'objectDescription' => 'Este OA contiene las generalidades de la administración y del sistema de gestión de calidad ISO 9001.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Calidad, Administración, Gestión ISO, Proceso',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724993/thumbnails/conceptos-modernos-de-administracion.png',
				'objectYoutube' => '_DiqPZ_eojE',
				'objectFormat' => 'SCORM',
				'objectSize' => '207 Mb',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => 'Montar en plataforma Moodle',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2016-07-08',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 5,
				'objectViews' => 17,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'creacion-de-empresas',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/creacion-de-empresas.zip',
				'objectTitle' => 'Creación de Empresas',
				'objectDescription' => 'En este objeto se muestran diferentes etapas de estudio de mercados con el fin de crear una empresa innovadora y competitiva.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Cliente, Competencia, Mercado, Economía, Gestión humana, Producto, Servicio, Oferta, Demanda, Precio, Consumidor, PIB',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724997/thumbnails/creacion-de-empresas.png',
				'objectYoutube' => 'IxymdRSyQvI',
				'objectFormat' => 'SCORM',
				'objectSize' => '176 Mb',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => 'Montar en plataforma Moodle',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2016-07-08',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 5,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'finanzas',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/finanzas.zip',
				'objectTitle' => 'Finanzas',
				'objectDescription' => 'Este OA cuenta con temas sobre tasas de interés simple y compuesto a un capital.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Finanzas, Dinero, Tasa de interés, Interés simple, Interés compuesto, Mercado, Costo, Beneficio, Capital, Valor, Utilidad, Ingreso, Egreso',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724998/thumbnails/finanzas.png',
				'objectYoutube' => 'CDeLbAcBgW8',
				'objectFormat' => 'SCORM',
				'objectSize' => '112 Mb',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => 'Montar en plataforma Moodle',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2016-07-08',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '1970-01-01 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 5,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'calidad-en-la-edificacion',
				'objectArea' => 'Ingeniería, arquitectura, urbanismo',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/calidad-en-la-edificacion.zip',
				'objectTitle' => 'Calidad en la edificación',
				'objectDescription' => 'Este objeto muestra la manera de Implementar en los proyectos de edificación los conceptos que puntualizan en el control de calidad.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Edificación, Calidad, Gestión, Construcción, Materiales, Procesos, Proyecto',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724986/thumbnails/calidad-en-la-edificacion.png',
				'objectYoutube' => 's2ISQMLAcbc',
				'objectFormat' => 'SCORM',
				'objectSize' => '139 Mb',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => 'Montar en plataforma Moodle',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2016-07-08',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 6,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'como-empezar-una-investigacion',
				'objectArea' => 'Ciencias sociales y humanas',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/como-empezar-una-investigacion.zip',
				'objectTitle' => '¿Cómo empezar una investigación?',
				'objectDescription' => 'Estudiar y aplicar herramientas que permiten un conocimiento profundo del público y del contexto en el que se implementa una idea de negocio.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Entrevista, Grupo Focal, Etnografía, Público Objetivo, Entrevista Estructurada, Entrevista Semiestructurada, Entrevista No Estructurada, Etnografía, Emprendimiento, Emprendedor, Mercado, Empresa',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724987/thumbnails/como-empezar-una-investigacion.png',
				'objectYoutube' => 'IGNxVh3BxTw',
				'objectFormat' => 'SCORM',
				'objectSize' => '68.7 Mb',
				'objectRequirement' => 'individual,colectivo, lider Formato => zip Requerimientos => Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => sietic@unicolmayor.edu.co Rol => Autor Fecha => 2015-05-21',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 4,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'como-hago-operaciones-basicas-y-creo-graficas-en-una-hoja-de-calculo',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Procedimental',
				'objectHosting' => '/storage/como-hago-operaciones-basicas-y-creo-graficas-en-una-hoja-de-calculo.zip',
				'objectTitle' => '¿Cómo hago operaciones básicas y creo gráficas en una hoja de cálculo?',
				'objectDescription' => 'Reconocer los componentes generales y específicos para desarrollar operaciones matemáticas básicas y elaborar gráficas en la hoja de cálculo.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Interpretar,Argumentar,Operadores,Operadores Lógicos,Expresiones,Sintaxis,Diagramas,Manejo Operativo',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724988/thumbnails/como-hago-operaciones-basicas-y-creo-graficas-en-una-hoja-de-calculo.png',
				'objectYoutube' => '2s0MPhFlByw',
				'objectFormat' => 'SCORM',
				'objectSize' => '46.1 MB',
				'objectRequirement' => 'Navegador => Explorer 10+, Chrome43+, Firefox 37+, Safari5+',
				'objectInstructions' => 'Subir Scorm a LMS',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => sietic@unicolmayor.edu.co Rol => Autor Fecha => 2015-06-19',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Economía, administración, contaduría y afines Ingeniería, arquitectura, urbanismo y afines',
				'objectTaxonomy' => 5,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'comunicacion-y-oralidad',
				'objectArea' => 'Ciencias sociales y humanas',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/comunicacion-y-oralidad.zip',
				'objectTitle' => 'Comunicación y oralidad',
				'objectDescription' => 'Comunicación y oralidad es un objeto de aprendizaje para que pueda entender cómo comunicarse y en qué forma darse a entender mejor',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'comunicacion, oralidad, entender',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724992/thumbnails/comunicacion-y-oralidad.png',
				'objectYoutube' => 'WGLXA7cGch8',
				'objectFormat' => 'SCORM',
				'objectSize' => '4.98 MB',
				'objectRequirement' => 'individual,colectivo, lider Formato => zip Requerimientos => Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '2.0',
				'objectContributors' => '',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Medio',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 4,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'tres-estilos-de-comunicacion-inadecuados-y-uno-asertivo',
				'objectArea' => 'Ciencias sociales y humanas',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/tres-estilos-de-comunicacion-inadecuados-y-uno-asertivo.zip',
				'objectTitle' => 'Tres estilos de comunicación inadecuados y uno asertivo',
				'objectDescription' => 'Este Objeto de Aprendizaje Complementario, acerca de tres estilos de comunicación inadecuados y uno asertivo. Está diseñado para que aprenda sobre las diferencias y su importancia.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'herramientas, verbal, deferencias, inadecuados, asertivo',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607725007/thumbnails/tres-estilos-de-comunicacion-inadecuados-y-uno-asertivo.png',
				'objectYoutube' => 'Iw7KtYScNQY',
				'objectFormat' => 'SCORM',
				'objectSize' => '25.9 MB',
				'objectRequirement' => 'individual,colectivo, lider Formato => zip Requerimientos => Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '2.0',
				'objectContributors' => '',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Bajo',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 4,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'investigacion-y-desarrollo',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/investigacion-y-desarrollo.zip',
				'objectTitle' => 'Investigación y desarrollo',
				'objectDescription' => 'En este OA se encuentran los procesos para realizar un anteproyecto de investigación y su posterior desarrollo como proyecto mediante la creación de empresa.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Investigación, Proyecto, Anteproyecto, Idea, Negocio, Empresa, Objetivos, Objetivo general, Objetivos específicos',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607725001/thumbnails/investigacion-y-desarrollo.png',
				'objectYoutube' => 'XIZHVvx2jM8',
				'objectFormat' => 'SCORM',
				'objectSize' => '155 MB',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2016-07-08',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 5,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'el-buen-vivir-de-otra-sociedad',
				'objectArea' => 'Ciencias sociales y humanas',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/el-buen-vivir-de-otra-sociedad.zip',
				'objectTitle' => 'El buen vivir de otra sociedad',
				'objectDescription' => 'Este objeto de aprendizaje estudia las diferencias del concepto del buen vivir en las diferentes culturas y sociedades',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Sociedad,Cultura,Buen vivir,Estructura social',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724997/thumbnails/el-buen-vivir-de-otra-sociedad.png',
				'objectYoutube' => 'qe4Znma9Fi0',
				'objectFormat' => 'SCORM',
				'objectSize' => '15.3 MB',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2014-02-15',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Bajo',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 4,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'metodologia-de-la-investigacion',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/metodologia-de-la-investigacion.zip',
				'objectTitle' => 'Metodología de la investigación',
				'objectDescription' => 'En este objeto se muestran las estrategias para la recopilación, interpretación y análisis de la información basándose en los fundamentos de la metodología de investigación.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Investigación, Metodología, Problema, Normas APA, Observación, Idea',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607725004/thumbnails/metodologia-de-la-investigacion.png',
				'objectYoutube' => '8t7hg4BxKxY',
				'objectFormat' => 'SCORM',
				'objectSize' => '95.5 MB',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2016-07-08',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 5,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'como-utilizo-funciones-basicas-en-una-hoja-de-calculo',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/como-utilizo-funciones-basicas-en-una-hoja-de-calculo.zip',
				'objectTitle' => '¿Cómo utilizo funciones básicas en una hoja de cálculo?',
				'objectDescription' => 'Identificar los componentes generales y específicos para la aplicabilidad de las funciones lógicas en la administración de datos en una hoja de cálculo.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Funciones,Argumentos Lógicos,Sintaxis,Simbología',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724990/thumbnails/como-utilizo-funciones-basicas-en-una-hoja-de-calculo.png',
				'objectYoutube' => 'QHmzdEpYnKo',
				'objectFormat' => 'SCORM',
				'objectSize' => '46.9 MB',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => sietic@unicolmayor.edu.co Rol => Autor Fecha => 2015-07-24',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Economía, administración, contaduría y afines Ingeniería, arquitectura, urbanismo y afines',
				'objectTaxonomy' => 5,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'la-solidaridad-fundamento-para-convivir',
				'objectArea' => 'Ciencias sociales y humanas',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/la-solidaridad-fundamento-para-convivir.zip',
				'objectTitle' => 'La solidaridad fundamento para convivir',
				'objectDescription' => 'Este objeto de aprendizaje muestra los diversos estilos de comunicarse con los demás y detalla las características de una comunicación asertiva',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Convivencia,Valores',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607725002/thumbnails/la-solidaridad-fundamento-para-convivir.png',
				'objectYoutube' => 'Gks_OD9XGhA',
				'objectFormat' => 'SCORM',
				'objectSize' => '22.9 MB',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2014-02-15',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Bajo',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 4,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'formulacion-y-evaluacion-de-proyectos',
				'objectArea' => 'Economía, administración, contaduría',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/formulacion-y-evaluacion-de-proyectos.zip',
				'objectTitle' => 'Formulación y evaluación de proyectos',
				'objectDescription' => 'Este OA contiene el concepto de proyecto, la importancia de los procesos de participación de un proyecto, teniendo en cuenta las etapas básicas que hacen parte de la estructuración del mismo.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Proyectos, Administración, Evaluación, Inversión, Eficiencia, Mercado, Competencia, Precios, Compromiso, Emprender',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607724999/thumbnails/formulacion-y-evaluacion-de-proyectos.png',
				'objectYoutube' => 'RgjEK0z54RM',
				'objectFormat' => 'SCORM',
				'objectSize' => '97.0 MB',
				'objectRequirement' => 'Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => lcorrales@unicolmayor.edu.co Rol => Autor Fecha => 2016-07-08',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Alto',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 5,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'la-informatica-y-la-ofimatica',
				'objectArea' => 'Ingeniería, arquitectura, urbanismo',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/la-informatica-y-la-ofimatica.zip',
				'objectTitle' => 'La informática y la Ofimática',
				'objectDescription' => 'Este objeto de aprendizaje introductorio , acerca de la informática sus aspectos principales, el cual está diseñado para que usted fortaleza sus conceptos acerca de la informática, su relación con la ofimática y sus diferencias.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => 'Proyectos, Administración, Evaluación, Inversión, Eficiencia, Mercado, Competencia, Precios, Compromiso, Emprender',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607725002/thumbnails/la-informatica-y-la-ofimatica.png',
				'objectYoutube' => 'p1ThpBxzGjo',
				'objectFormat' => 'SCORM',
				'objectSize' => '9.00 MB',
				'objectRequirement' => 'Individual,colectivo, lider Formato => zip Requerimientos => Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => 'Nombres => Universidad Colegio Mayor de Cundinamarca Organización => Universidad Colegio Mayor de Cundinamarca Correo => sietic@unicolmayor.edu.co Rol => Autor Fecha => 2016 – 01- 19',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '2020-07-07 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Medio',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 5,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'guia-de-quimica-determinacion-del-ph',
				'objectArea' => 'Mediaciones',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/guia-de-quimica-determinacion-del-ph.zip',
				'objectTitle' => 'Guía de Química - Determinación del PH',
				'objectDescription' => 'Este objeto de aprendizaje introductorio , acerca de cómo determinar el PH.',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => '',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607725000/thumbnails/guia-de-quimica-determinacion-del-ph.png',
				'objectYoutube' => 'IpfzPWVuypA',
				'objectFormat' => 'SCORM',
				'objectSize' => '8.60 MB',
				'objectRequirement' => 'Individual,colectivo, lider Formato => zip Requerimientos => Sistema operativo => Windows, Linux, Macintosh. Navegador => Explorer 8+, Chrome10+, Firefox 5+',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => '',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '0000-00-00T00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Medio',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 9,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'modelo-de-preferencias',
				'objectArea' => 'Mediaciones',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/modelo-de-preferencias.zip',
				'objectTitle' => 'Modelo de preferencias',
				'objectDescription' => 'Investigación institucional 2018',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => '',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607725005/thumbnails/modelo-de-preferencias.png',
				'objectYoutube' => 'LptjEKzKfsw',
				'objectFormat' => 'SCORM',
				'objectSize' => '7.58 MB',
				'objectRequirement' => '',
				'objectInstructions' => '',
				'objectVersion' => '1.0',
				'objectContributors' => '',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '0000-00-00T00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Bajo',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 9,
				'objectViews' => 0,
				'isObjectActive' => 1
			],
			[
				'objectObject' => 'origami',
				'objectArea' => 'Ciencias Básicas',
				'objectKnowlessTopic' => 'Conceptual',
				'objectHosting' => '/storage/origami.zip',
				'objectTitle' => 'Origami',
				'objectDescription' => '',
				'objectLanguage' => 'Es(español)',
				'objectKeyWords' => '',
				'objectLink' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607725005/thumbnails/origami.png',
				'objectYoutube' => 'f7cACuAxAgg',
				'objectFormat' => 'SCORM',
				'objectSize' => '32.9 MB',
				'objectRequirement' => '',
				'objectInstructions' => '',
				'objectVersion' => '1',
				'objectContributors' => '',
				'objectEntities' => 'Universidad Colegio Mayor de Cundinamarca',
				'objectCreatedAt' => '1970-01-01 00:00:00',
				'objectTopic' => null,
				'objectInteractivity' => 'Bajo',
				'objectCost' => 'Este material es libre de costos',
				'objectRights' => 'Licencia Creative Commons by-nc-nd (Atribución, no comercial, sin cambios)',
				'objectUse' => 'Educativo',
				'objectClasification' => 'Áreas de Conocimiento - NBC',
				'objectTaxonomy' => 9,
				'objectViews' => 0,
				'isObjectActive' => 1
			]
		];

		$builder = $this->db->table('objects');
		$builder->insertBatch($objects);
	}
}
