<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class InitTools extends Seeder
{
	public function run()
	{
		$tools = [
			[
				'toolName' => 'Socrative',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=cddfeyfgfAE',
				'toolDescription' => '<p>https://www.socrative.com/</p><p>Su aplicación para el aula para una participación divertida, efectiva y evaluaciones sobre la marcha. </p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741351/herramientas/hero-blog-2000x784_ikjkp7.jpg',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Flipsnack',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=xgpDXzwxpFs',
				'toolDescription' => '<p>https://www.flipsnack.com/</p><p>Generador de flipboook digitales para revistas impactantes Crea y comparte revistas en línea, transformando tus PDF en flipbook en línea.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741750/herramientas/first_video_frame_n9i66c.webp',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Blendspace',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=E17LLvqmnRQ',
				'toolDescription' => '<p>https://www.tes.com/lessons</p><p> </p><p>Para crear lecciones enriquecidas con todo tipo de material (incluyendo contenido web) y compartirlas permitiendo siempre su cómoda visualización.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607743506/herramientas/blendspace_mkrfsp.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Ted Education',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=6Pg_yrlzY5M',
				'toolDescription' => '<p>https://ed.ted.com</p><p> </p><p>Una sección de TED (un portal con “miles de conferencias en video, sobre centenares de áreas del conocimiento, dadas por expertos de talla mundial”)</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/teded-logo-600-600_k6wxmb.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Emaze',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=LdYcTUWsR9o',
				'toolDescription' => '<p>Generar presentaciones digitales increíbles automáticamente</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/emaze_logo_square_vwikhc.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'VideoScribe',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=HT8duZRS38A',
				'toolDescription' => '<p>Haga su propio video de pizarra rápidamente VideoScribe es fácil, rápido y económico. ¡Puedes crear un gran video en poco tiempo!</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/maker-faire-video-scribe-instructions-1-638_qhlrp2.jpg',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Animoto',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=yqx0h_ipyMo',
				'toolDescription' => '<p>Realización de vídeos de forma sencilla</p><p>Únase a millones de personas que crean y comparten videos con nuestro sencillo creador de videos de arrastrar y soltar. No se requiere experiencia.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741351/herramientas/c%C3%B3mo-funciona-animoto_xtfmzx.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Picmonkey',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=39gdq3z1MG4',
				'toolDescription' => '<p>Potencia tu marca con edición y diseño de fotografías Cree imágenes de parada de desplazamiento para Facebook, Instagram, Youtube y más. ¿Anuncios, logotipos? Ellos tambien.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741349/herramientas/PicMonkey_Logo1_ritsxi.jpg',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Genially.ly',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=xduPwwgx5Ls',
				'toolDescription' => '<p>La herramienta que millones de personas usan para crear presentaciones, infografías y mucho más. Convierte tus ideas en experiencias</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741349/herramientas/logo-genially_azpwiu.jpg',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Typeform',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=VpqlJ0VFYoE',
				'toolDescription' => '<p>Formularios y encuestas amigables para las personas. Convierta una lista de preguntas en una conversación amistosa. Y obtenga mejores datos.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/meta_Homepage_bararo.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Storybird',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=pg0fHgsPx4o',
				'toolDescription' => '<p>Mejore sus habilidades de escritura con más de 700 desafíos creados por educadores profesionales y autores expertos.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/Storybird_duhz8r.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'DrawExpress',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=bEmJiz4D5s8',
				'toolDescription' => '<p>Mapas conceptuales faciles dibujos</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/unnamed_cuonow.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Coggle',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=rj1Q0l804vU',
				'toolDescription' => '<p>La forma fácil de compartir información compleja.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/coggle-banner-green_myzwdf.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Popplet',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=WRjyfqa8VT4',
				'toolDescription' => '<p>Popplet ayuda a capturar, visualizar, organizar y compartir ideas. Úselo para crear todo, desde listas simples hasta líneas de tiempo y telarañas complejas. Con texto, imágenes y video, Popplet funciona en todos los idiomas y en ningún idioma.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/popplet-1-638_nfthfq.jpg',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Proprof',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=yzrasWD1TYM',
				'toolDescription' => '<p>Creamos herramientas de software que le ayudan a tener empleados más inteligentes y clientes más felices</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/unnamed_1_b5rg0q.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Quizbean',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=ITLrqGXeD_E',
				'toolDescription' => '<p>Creador de cuestionarios</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741350/herramientas/QuizBean-1-350x231_ee3se4.jpg',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Evernote',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=jJB8kztrJ1A',
				'toolDescription' => '<p>Tus notas. Organizadas. Sin esfuerzo toma notas desde cualquier lugar. Encuentra la información rápidamente. Comparte ideas con quien quieras. Notas de reuniones, páginas web, proyectos y listas de tareas, con Evernote no perderás nada.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741351/herramientas/evernote-og-900x439_etr4s1.png',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Cómo hacer infografias con Canva',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=5CHdSrhHr5M',
				'toolDescription' => '<p>Tutorial Canva en español.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741351/herramientas/hqdefault_1_lnzflj.jpg',
				'toolRole' => 3,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Cómo crear una Infografía en Piktochart',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=RJM2Q6WiqQ0',
				'toolDescription' => '<p>Herramienta para crear infografías, elementos gráficos e ilustraciones.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741349/herramientas/hqdefault_mw0q7z.jpg',
				'toolRole' => 3,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Tutorial herramienta Easelly',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=AiQX-DPe74c',
				'toolDescription' => '<p>Muestra el uso básico de la herramienta Easelly.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741349/herramientas/hqdefault_5_sliptz.jpg',
				'toolRole' => 3,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Programas para hacer infografías',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=Hx3Ar5z1vG8',
				'toolDescription' => '<p>Top 5 de los mejores programas gratis para hacer infografías.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741351/herramientas/hqdefault_3_c5hzm3.jpg',
				'toolRole' => 3,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Tutorial Wordle',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=scLH-HkcPfY',
				'toolDescription' => '<p>Cómo realizar una nube de palabras.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741351/herramientas/hqdefault_4_csojlp.jpg',
				'toolRole' => 3,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Videotutorial Powtoon',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=JCM2cIxORC4',
				'toolDescription' => '<p>Herramienta para crear presentaciones animadas de una manera sencilla.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741349/herramientas/hqdefault_6_suzgoa.jpg',
				'toolRole' => 3,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'Web del Maestro',
				'toolNameUrl' => 'https://webdelmaestrocmf.com/portal/',
				'toolDescription' => '<p>Web con ideas de prefesores para profesores.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741349/herramientas/logo_af2cbf.jpg',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'EaseUS Programa para Editar Vídeos',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=dNZ2i_eV9R4',
				'toolDescription' => '<p>Programa de edición de vídeo muy sencillo de utilizar.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741351/herramientas/hqdefault_2_x4g7hi.jpg',
				'toolRole' => 3,
				'isToolActive' => 1,
			],
			[
				'toolName' => 'EaseUS Programa para Editar Vídeos',
				'toolNameUrl' => 'https://www.youtube.com/watch?v=dNZ2i_eV9R4',
				'toolDescription' => '<p>Programa de edición de vídeo muy sencillo de utilizar.</p>',
				'toolImageUrl' => 'https://res.cloudinary.com/un1c0lm4y0r/image/upload/v1607741351/herramientas/hqdefault_2_x4g7hi.jpg',
				'toolRole' => 4,
				'isToolActive' => 1,
			],
		];

		$builder = $this->db->table('tools');
		$builder->insertBatch($tools);
	}
}
